#!/bin/sh
CMD=$(echo "$@" | cut -d " " -f 1)

if [ $CMD == "archive" ]; then
    while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -X POST 127.0.0.1:3500/v1.0/shutdown)" != "204" ]]; do sleep 1; done
fi

exec xk6 "$@"